server:
  servlet:
    context-path: /api

spring:
  profiles: localH2
  transaction: TRACE
  datasource:
    url: jdbc:h2:mem:test2;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    .properties:
      hibernate:
        format_sql:true:
  logging:
    level:
      org:
        hibernate:
          .type:
            descriptor:
              sql:trace:
          SQL:debug:
  ###
  #  H2 Settings
  ###
  h2:
    console:
      enabled: true